In [1]:
import pandas as pd

In [2]:

# Skapa två vektorer
df = pd.DataFrame({
    "dimension": ["x", "y", "z"],
    "vektor_u": [2, 4, 1],
    "vektor_v": [3, -1, 5]
})

df

  dimension  vektor_u  vektor_v
0         x         2         3
1         y         4        -1
2         z         1         5

In [3]:
df = pd.DataFrame({
    "dimension": ["x", "y", "z"],
    "vektor_u": [2, 4, 1]
})

skalär = 3
df["3 * u"] = df["vektor_u"] * skalär

df

  dimension  vektor_u  3 * u
0         x         2      6
1         y         4     12
2         z         1      3

In [4]:
df["-2 * u"] = df["vektor_u"] * -2
df

  dimension  vektor_u  3 * u  -2 * u
0         x         2      6      -4
1         y         4     12      -8
2         z         1      3      -2

In [5]:

df = pd.DataFrame({
    "dimension": ["x", "y", "z"],
    "u": [2, 4, 1],
    "v": [3, -1, 5]
})

df["u * v"] = df["u"] * df["v"]
df

  dimension  u  v  u * v
0         x  2  3      6
1         y  4 -1     -4
2         z  1  5      5

In [6]:
skalärprodukt = df["u * v"].sum()
print("Skalärprodukt u · v =", skalärprodukt)

Skalärprodukt u · v = 7

In [7]:
df = pd.DataFrame({
    "namn": ["A", "B", "C", "D"],
    "x": [1, 2, -1, 3],
    "y": [4, 0, 2, 1]
})

df

  namn  x  y
0    A  1  4
1    B  2  0
2    C -1  2
3    D  3  1

In [8]:
df["2x"] = 2 * df["x"]
df["2y"] = 2 * df["y"]

df

  namn  x  y  2x  2y
0    A  1  4   2   8
1    B  2  0   4   0
2    C -1  2  -2   4
3    D  3  1   6   2

In [9]:
df = pd.DataFrame({
    "moment": ["Quiz", "Laboration", "Prov"],
    "elev_A": [8, 15, 20],
    "elev_B": [7, 18, 16]
})

df["produkt"] = df["elev_A"] * df["elev_B"]
df

       moment  elev_A  elev_B  produkt
0        Quiz       8       7       56
1  Laboration      15      18      270
2        Prov      20      16      320

In [10]:
dot_product = df["produkt"].sum()
print("Skalärprodukt =", dot_product)

Skalärprodukt = 646

In [11]:
def skalärprodukt(v1, v2):
    df = pd.DataFrame({
        "v1": v1,
        "v2": v2
    })
    df["produkt"] = df["v1"] * df["v2"]
    print(df)
    return df["produkt"].sum()

resultat = skalärprodukt([2, 4, 1], [3, -1, 5])
print("Skalärprodukt =", resultat)

   v1  v2  produkt
0   2   3        6
1   4  -1       -4
2   1   5        5
Skalärprodukt = 7

In [13]:
import numpy as np

u = np.array([2, 4, 1])
v = np.array([3, -1, 5])

df = pd.DataFrame({
    "dimension": ["x", "y", "z"],
    "u": u,
    "v": v,
    "u*v": u * v
})

display(df)

print("Skalärprodukt:", np.dot(u, v))
print("2u:", 2 * u)

  dimension  u  v  u*v
0         x  2  3    6
1         y  4 -1   -4
2         z  1  5    5

Skalärprodukt: 7
2u: [4 8 2]

In [14]:
# Definiera två vektorer
u = [2, 4, 1]
v = [3, -1, 5]

df = pd.DataFrame({
    "dimension": ["x", "y", "z"],
    "u": u,
    "v": v
})

print("Originalvektorer:")
display(df)

# Skalärmultiplikation
df["2u"] = df["u"] * 2
df["-3v"] = df["v"] * -3

print("Efter skalärmultiplikation:")
display(df)

# Skalärprodukt steg för steg
df["u*v"] = df["u"] * df["v"]

print("Komponentvis multiplikation:")
display(df)

skalärprodukt = df["u*v"].sum()
print("Skalärprodukt u · v =", skalärprodukt)

Originalvektorer:

  dimension  u  v
0         x  2  3
1         y  4 -1
2         z  1  5

Efter skalärmultiplikation:

  dimension  u  v  2u  -3v
0         x  2  3   4   -9
1         y  4 -1   8    3
2         z  1  5   2  -15

Komponentvis multiplikation:

  dimension  u  v  2u  -3v  u*v
0         x  2  3   4   -9    6
1         y  4 -1   8    3   -4
2         z  1  5   2  -15    5

Skalärprodukt u · v = 7